# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45b2b3b68d9860b930add2086412fd48dacadd52c72d9630236df0e1d2ecb7383efc97a24abbe163be925adedeb8124a462409f361ca7e4fe22fba94c53b2b4

test:
  secret_key_base: 2cb5c5efa5a5a77fa4a2d481ccbe48ea7f707becd2584a093192844e252bb52e390b3d2d200b0e424864dc6f53becaafef180442031ac7fb06a88513d609f818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
